name: Build
run-name: Build be ${{ github.actor }} 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Build Dependencies
        run: |
         sudo apt-get install -y cmake ninja-build openjdk-17-jdk libgl1-mesa-dev zlib1g-dev qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools libqt5core5a libqt5network5 libqt5gui5 qt5-image-formats-plugins scdoc extra-cmake-modules

      - name: Fetching latest release
        run: |
          git clone https://github.com/TCGamersPT/ModdedPrismLauncher.git

      - name: Install makedeb
        run: |
          wget -qO - 'https://proget.makedeb.org/debian-feeds/makedeb.pub' | gpg --dearmor | sudo tee /usr/share/keyrings/makedeb-archive-keyring.gpg 1> /dev/null
          echo 'deb [signed-by=/usr/share/keyrings/makedeb-archive-keyring.gpg arch=all] https://proget.makedeb.org/ makedeb main' | sudo tee /etc/apt/sources.list.d/makedeb.list
          sudo apt-get -y update && sudo apt-get -y install makedeb          

      - name: Making .deb file 
        run: |
          cd ModdedPrismLauncher/
          cd .github/
          cd makedeb/
          makedeb
