name: Build
run-name: Build be ${{ github.actor }} 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Build Dependencies
        run: |
         sudo apt-get install -y cmake ninja-build openjdk-17-jdk libgl1-mesa-dev zlib1g-dev qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools libqt5core5a libqt5network5 libqt5gui5

      - name: Fetching latest release
        run: |
          git clone https://github.com/TCGamersPT/ModdedPrismLauncher.git

      - name: Install makedeb
        run: |
          set +x
          bash -ci "$(wget -qO - 'https://shlink.makedeb.org/install')"

      - name: Making .deb file 
        run: |
          cd ModdedPrismLauncher/
          cd .github/
          cd makedeb/
          makedeb
